### ISSUE TITLE
Could not find module "ngxs-schematics"

### ISSUE THREAD

**Issue by dalu** [ngxs/schematics#12]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/ngxs/store/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior
```
ng g lib --help
Could not find module "ngxs-schematics" from "/home/darko/WebstormProjects/community".
Error: Could not find module "ngxs-schematics" from "/home/darko/WebstormProjects/community".
    at Object.resolve (/home/darko/WebstormProjects/community/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at NodeModulesEngineHost._resolvePackageJson (/home/darko/WebstormProjects/community/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:28:21)
    at NodeModulesEngineHost._resolveCollectionPath (/home/darko/WebstormProjects/community/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:69:40)
    at NodeModulesEngineHost.createCollectionDescription (/home/darko/WebstormProjects/community/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:111:27)
    at SchematicEngine._createCollectionDescription (/home/darko/WebstormProjects/community/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/home/darko/WebstormProjects/community/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at GenerateCommand.getCollection (/home/darko/WebstormProjects/community/node_modules/@angular/cli/models/schematic-command.js:123:35)
    at GenerateCommand.initialize (/home/darko/WebstormProjects/community/node_modules/@angular/cli/commands/generate-impl.js:19:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
```

## Expected behavior

No error

## Minimal reproduction of the problem with instructions

add schematics
try to do anything involving generation

## Environment

<pre><code>
Libs:
- @angular/core version: 7.1.0
- @ngxs/store version: 3.2.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.11.0
- Platform: Linux

Others:
</code></pre>

**Comment by dalu** [comment]
It's because in angular.json default schematics are set to this but for w/e reason it can't be found.

**Comment by markwhitfeld** [comment]
Did you install the schematics using `@ngxs/schematics`?

**Comment by dalu** [comment]
Yes, via ng add.
```
{
  "name": "community",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.1.0",
    "@angular/cdk": "~7.1.0",
    "@angular/common": "~7.1.0",
    "@angular/compiler": "~7.1.0",
    "@angular/core": "~7.1.0",
    "@angular/forms": "~7.1.0",
    "@angular/material": "^7.1.0",
    "@angular/platform-browser": "~7.1.0",
    "@angular/platform-browser-dynamic": "~7.1.0",
    "@angular/router": "~7.1.0",
    "@ngxs/devtools-plugin": "^3.2.0",
    "@ngxs/logger-plugin": "^3.2.0",
    "@ngxs/router-plugin": "^3.3.1",
    "@ngxs/schematics": "^0.0.1-alpha.0",
    "@ngxs/store": "^3.2.0",
    "angular-oauth2-oidc": "^5.0.2",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular-devkit/build-ng-packagr": "~0.11.0",
    "@angular/cli": "~7.1.0",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^4.2.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}
```
